/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as KiosksIndexImport } from './routes/kiosks/index'
import { Route as ChangelogIndexImport } from './routes/changelog/index'
import { Route as KiosksKioskIdImport } from './routes/kiosks/$kioskId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const KiosksIndexRoute = KiosksIndexImport.update({
  path: '/kiosks/',
  getParentRoute: () => rootRoute,
} as any)

const ChangelogIndexRoute = ChangelogIndexImport.update({
  path: '/changelog/',
  getParentRoute: () => rootRoute,
} as any)

const KiosksKioskIdRoute = KiosksKioskIdImport.update({
  path: '/kiosks/$kioskId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/kiosks/$kioskId': {
      id: '/kiosks/$kioskId'
      path: '/kiosks/$kioskId'
      fullPath: '/kiosks/$kioskId'
      preLoaderRoute: typeof KiosksKioskIdImport
      parentRoute: typeof rootRoute
    }
    '/changelog/': {
      id: '/changelog/'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogIndexImport
      parentRoute: typeof rootRoute
    }
    '/kiosks/': {
      id: '/kiosks/'
      path: '/kiosks'
      fullPath: '/kiosks'
      preLoaderRoute: typeof KiosksIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  KiosksKioskIdRoute,
  ChangelogIndexRoute,
  KiosksIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/kiosks/$kioskId",
        "/changelog/",
        "/kiosks/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/kiosks/$kioskId": {
      "filePath": "kiosks/$kioskId.tsx"
    },
    "/changelog/": {
      "filePath": "changelog/index.tsx"
    },
    "/kiosks/": {
      "filePath": "kiosks/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
